entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: aaron.saada0@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web
